const mongoose=require("mongoose");
const user=new mongoose.Schema({
    username:{
        type:String,
        required:true,
        unique:true,
    },
     email:{
        type:String,
        required:true,
        unique:true,
    },
    password:{
        type:String,
        required:true,
    },
    address:{
        type:String,
        required:true,
    },
    avatar:{
        type:String,
        default:"https://cdn-icons-png.flaticon.com/512/149/149071.png",
    },
    role:{
        type:String,
        default:"user",
        enum:["user","admin"],
    },
    favourites:[
        {
        type:mongoose.Types.ObjectId,
        ref:"Books",
        },
    ],
    carts:[
        {
        type:mongoose.Types.ObjectId,
        ref:"Books",
        },
    ],
    orders:[
        {
        type:mongoose.Types.ObjectId,
        ref:"orders",
        },
    ],
},
    {timestamps:true}             //to put recent users at the top of the list
);
module.exports=mongoose.model("users",user);